### ISSUE TITLE
Decorating polyline with arrows or icons

### ISSUE THREAD

**Issue by rajeevaswani10** [mstahv/v-leaflet#175]
Found a javascript which does this smoothly.
https://github.com/bbecquet/Leaflet.PolylineDecorator

Facing hard time to integrate in vaadin / v-leaflet framework.

Please please please help ?  Any pointers would be appreciated.

One question

I needed an LeafletPolylineDecoratorConnector derived from AbstractLeafletVectorConnector   just exactly like LeafletPolylineConnector but   can't derive fom AbstractLeafletvectorConnector class.

**Comment by rajeevaswani10** [comment]
I can achieve the same if AbstractLeafletVectorConnector  ctor is made protected / public     

Is it possible as part of this fix ?

**Comment by mstahv** [comment]
Hi, looks quite handy extension, would be great to have v-leaflet counterpart for that.

I think the constructor was package private by mistake, opened in https://github.com/mstahv/v-leaflet/commit/7524612daa037b78acbbee2c8e8a7eb1c45c7ec5

Will build a new version right away. Let me know if you need any further help with the integration. It is not easy to start the setup, but there are quite many examples in https://vaadin.com/directory how it can be done.

**Comment by mstahv** [comment]
I also hope you can publish the extension to the Directory when it is done, I'm sure it will have other happy users as well!

**Comment by mstahv** [comment]
Hi Rajeev,

Quickly looking at the code, I'd say that there is nothing which is injecting the decorator script to the "host page".

Instead of adding the feature directly to the v-leaflet project, I'd suggest to look into some v-leaflet extensions, which are like plugins to v-leaflet. 

Here is one example (it contains separate gwt project, in this case it can be the same or you could put all into a vaadin integration as well for simplicity):
https://github.com/willtemperley/v-leaflet-markercluster-parent/

cheers,
matti
