### ISSUE TITLE
Map with only one point does not display

### ISSUE THREAD

**Issue by slibert** [mstahv/v-leaflet#76]
Hello Guys,

Really nice add-on, thanks for the efforts !
There is a small issue, but quite annoying, map is not displaying if it contains only a single point.
You can reproduce it even with the online demo (http://v3.tahvonen.fi/vleafletexample/)

Steps to reproduce : 
- Connect to DEMO : http://v3.tahvonen.fi/vleafletexample/
- Remove all points from the table
- Click "New event with location"
- Pick a point, anywhere, and save
=> Map is grey, empty, until you zoom in or zoom out

If it's not grey at this time, just make a browser reload, it will happend.

Sorry for not digging and giving a hint from the source code, but I'm really not confortable with mapping-api.

Regards

**Comment by mstahv** [comment]
Apparently the "zoomToContent" somehow breaks if there is only on point object that should be fitted for the UI. If I zoom out form the broken situation it seems to works again. Instead of trying to figure out the proper zoom level in this case, it should probably just center the viewport to given point if only one point is in the views.

**Comment by slibert** [comment]
Indeed, zoomToContent is the one I pointed out in the code.

Thanks for the advise, I just change my code and use now setView (lat, long, zoom), and it's working.

**Comment by mstahv** [comment]
Nice, the functionality in v-leaflet should be changed into something like this as well.
